import type { Expert, Category } from "@/types";

export const MOCK_EXPERTS: Expert[] = [
  {
    id: "1",
    display_name: "山田 太郎",
    license: "税理士",
    title: "法人税・決算・節税相談",
    bio: "中小企業向けの法人税務を中心に活動。節税や資金繰り改善のアドバイスが得意です。開業15年、相談実績1,000件以上。",
    location: "東京都 千代田区",
    price_label: "30分 / 無料",
    gender: "male",
    is_online: true,
    is_approved: true,
    is_priority: true,
    rating: 4.8,
    review_count: 132,
    tags: ["法人税", "節税", "資金繰り", "中小企業", "決算"],
    categories: ["tax", "startup"],
  },
  {
    id: "2",
    display_name: "佐藤 花子",
    license: "社会保険労務士",
    title: "労務管理・就業規則・助成金",
    bio: "就業規則の整備や労務トラブルの予防に注力。助成金申請のサポート経験も豊富です。",
    location: "大阪府 大阪市",
    price_label: "30分 / 無料",
    gender: "female",
    is_online: false,
    is_approved: true,
    is_priority: false,
    rating: 4.6,
    review_count: 89,
    tags: ["労基法", "就業規則", "助成金", "給与計算"],
    categories: ["labor"],
  },
  {
    id: "3",
    display_name: "鈴木 健一",
    license: "司法書士",
    title: "登記・相続・会社設立",
    bio: "会社設立や相続登記を中心にサポート。初めての手続きでも分かりやすく説明します。",
    location: "愛知県 名古屋市",
    price_label: "30分 / 無料",
    gender: "male",
    is_online: true,
    is_approved: true,
    is_priority: false,
    rating: 4.7,
    review_count: 76,
    tags: ["会社設立", "相続", "不動産登記"],
    categories: ["inheritance", "startup"],
  },
  {
    id: "4",
    display_name: "高橋 美咲",
    license: "行政書士",
    title: "許認可・契約書・ビザ申請",
    bio: "建設業許可や風俗営業許可など、許認可申請のスペシャリスト。外国人ビザ申請も対応。",
    location: "東京都 新宿区",
    price_label: "30分 / 無料",
    gender: "female",
    is_online: true,
    is_approved: true,
    is_priority: true,
    rating: 4.5,
    review_count: 64,
    tags: ["建設業許可", "契約書レビュー", "ビザ申請"],
    categories: ["license", "contract"],
  },
  {
    id: "5",
    display_name: "田中 誠",
    license: "中小企業診断士",
    title: "経営改善・補助金・資金調達",
    bio: "中小企業の経営改善や事業計画策定を支援。補助金申請の採択実績多数。",
    location: "福岡県 福岡市",
    price_label: "30分 / 無料",
    gender: "male",
    is_online: false,
    is_approved: true,
    is_priority: false,
    rating: 4.4,
    review_count: 51,
    tags: ["補助金", "事業計画", "資金調達", "経営改善"],
    categories: ["funding"],
  },
  {
    id: "6",
    display_name: "伊藤 由美",
    license: "税理士",
    title: "相続税・贈与税・資産承継",
    bio: "相続税専門の税理士。資産家のご家族の節税対策から申告まで丁寧にサポートします。",
    location: "東京都 港区",
    price_label: "30分 / 無料",
    gender: "female",
    is_online: true,
    is_approved: true,
    is_priority: false,
    rating: 4.9,
    review_count: 98,
    tags: ["相続税", "贈与税", "資産承継", "節税"],
    categories: ["inheritance", "tax"],
  },
];

export const MOCK_CATEGORIES: Category[] = [
  { id: 1, name: "税金・節税のこと", slug: "tax" },
  { id: 2, name: "会社設立・起業のこと", slug: "startup" },
  { id: 3, name: "相続・遺言のこと", slug: "inheritance" },
  { id: 4, name: "従業員・雇用のこと", slug: "labor" },
  { id: 5, name: "契約書・トラブルのこと", slug: "contract" },
  { id: 6, name: "許認可・申請のこと", slug: "license" },
  { id: 7, name: "資金調達・補助金のこと", slug: "funding" },
];
